#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main() {
    char *choices[] = {"Rock", "Paper", "Scissors"};
    int userChoice, compChoice;

    printf("Let's play Rock-Paper-Scissors!\n");
    printf("Enter your choice: (0) Rock, (1) Paper, (2) Scissors: ");
    scanf("%d", &userChoice);

    srand(time(0));
    compChoice = rand() % 3;

    printf("You chose: %s\n", choices[userChoice]);
    printf("Computer chose: %s\n", choices[compChoice]);

    if (userChoice == compChoice) {
        printf("It's a draw!\n");
    } else if ((userChoice == 0 && compChoice == 2) ||
               (userChoice == 1 && compChoice == 0) ||
               (userChoice == 2 && compChoice == 1)) {
        printf("You win! Congratulations!\n");
    } else {
        printf("You lose! Better luck next time!\n");
    }

    return 0;
}
/*Here’s a detailed explanation of the two lines:

---

### 1. **`srand(time(0));`**
- **Purpose**: Sets the seed for the random number generator.
- **How it works**:
  - The `srand()` function initializes the random number generator used by the `rand()` function.
  - `time(0)` returns the current time in seconds since the epoch (usually January 1, 1970). This ensures that the seed value is different each time the program is run, which makes the random numbers appear more unpredictable.
- Without `srand()`, the random numbers generated by `rand()` would be the same each time the program is executed.

---

### 2. **`compChoice = rand() % 3;`**
- **Purpose**: Generates a random number between `0` and `2` (inclusive).
- **How it works**:
  - The `rand()` function produces a pseudo-random integer.
  - The modulo operator (`% 3`) limits the result to the range `0` to `2` by dividing the random number by `3` and taking the remainder.
  - This is often used in games or simulations to randomly select an option from a small set (e.g., rock-paper-scissors choices: 0 = Rock, 1 = Paper, 2 = Scissors).

---

### Example Workflow:
1. **Set seed**:
   - `time(0)` returns the current time, e.g., `1700000000`.
   - `srand(1700000000)` initializes the random number generator.
2. **Generate random number**:
   - `rand()` produces a large pseudo-random number, e.g., `243856`.
   - `243856 % 3` results in `1` (the remainder when dividing by `3`).
   - `compChoice` is assigned the value `1`.

This approach ensures that each program run can generate different random choices for `compChoice`.*/
